# Generated by Django 5.0.3 on 2024-03-13 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipester', '0002_recipe_user_id_ingredient_recipe_ingredients_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ManyToManyField(related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
