# Generated by Django 5.0.3 on 2024-03-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipester', '0004_remove_recipe_user_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='site_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
