# Generated by Django 5.0.3 on 2024-03-18 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipester', '0005_recipe_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_range',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipester.quantityrange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='groups',
            field=models.ManyToManyField(to='recipester.recipegroup'),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(to='recipester.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ManyToManyField(to='recipester.unit'),
        ),
    ]
