# Generated by Django 5.0.3 on 2024-03-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipester', '0008_alter_ingredient_quantity_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
