# Generated by Django 5.0.3 on 2024-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipester', '0009_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ManyToManyField(null=True, to='recipester.unit'),
        ),
    ]
